/*
     NanoGUI was developed by Wenzel Jakob <wenzel.jakob@epfl.ch>.
     The widget drawing code is based on the NanoVG demo application
     by Mikko Mononen.

     All rights reserved. Use of this source code is governed by a
     BSD-style license that can be found in the LICENSE.txt file.

     This file represents the constants that can be used provided by the
     fontawesome font.

     License: CC-BY-SA 4.0: https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt
 */

/* Developer note: need to make a change to this file?
 * Please raise an Issue on GitHub describing what needs to change.  This file
 * was generated, so the scripts that generated it need to update as well.
 */

#pragma once

#define FONTAWESOME_ICON_ADDRESS_BOOK                              0x0000F100
#define FONTAWESOME_ICON_ADDRESS_CARD                              0x0000F101
#define FONTAWESOME_ICON_ARROW_ALT_CIRCLE_DOWN                     0x0000F102
#define FONTAWESOME_ICON_ARROW_ALT_CIRCLE_LEFT                     0x0000F103
#define FONTAWESOME_ICON_ARROW_ALT_CIRCLE_RIGHT                    0x0000F104
#define FONTAWESOME_ICON_ARROW_ALT_CIRCLE_UP                       0x0000F105
#define FONTAWESOME_ICON_BELL                                      0x0000F106
#define FONTAWESOME_ICON_BELL_SLASH                                0x0000F107
#define FONTAWESOME_ICON_BOOKMARK                                  0x0000F108
#define FONTAWESOME_ICON_BRANDS_500PX                              0x0000F109
#define FONTAWESOME_ICON_BRANDS_ACCESSIBLE_ICON                    0x0000F10A
#define FONTAWESOME_ICON_BRANDS_ACCUSOFT                           0x0000F10B
#define FONTAWESOME_ICON_BRANDS_ADN                                0x0000F10C
#define FONTAWESOME_ICON_BRANDS_ADVERSAL                           0x0000F10D
#define FONTAWESOME_ICON_BRANDS_AFFILIATETHEME                     0x0000F10E
#define FONTAWESOME_ICON_BRANDS_ALGOLIA                            0x0000F10F
#define FONTAWESOME_ICON_BRANDS_AMAZON                             0x0000F110
#define FONTAWESOME_ICON_BRANDS_AMAZON_PAY                         0x0000F111
#define FONTAWESOME_ICON_BRANDS_AMILIA                             0x0000F112
#define FONTAWESOME_ICON_BRANDS_ANDROID                            0x0000F113
#define FONTAWESOME_ICON_BRANDS_ANGELLIST                          0x0000F114
#define FONTAWESOME_ICON_BRANDS_ANGRYCREATIVE                      0x0000F115
#define FONTAWESOME_ICON_BRANDS_ANGULAR                            0x0000F116
#define FONTAWESOME_ICON_BRANDS_APP_STORE                          0x0000F117
#define FONTAWESOME_ICON_BRANDS_APP_STORE_IOS                      0x0000F118
#define FONTAWESOME_ICON_BRANDS_APPER                              0x0000F119
#define FONTAWESOME_ICON_BRANDS_APPLE                              0x0000F11A
#define FONTAWESOME_ICON_BRANDS_APPLE_PAY                          0x0000F11B
#define FONTAWESOME_ICON_BRANDS_ASYMMETRIK                         0x0000F11C
#define FONTAWESOME_ICON_BRANDS_AUDIBLE                            0x0000F11D
#define FONTAWESOME_ICON_BRANDS_AUTOPREFIXER                       0x0000F11E
#define FONTAWESOME_ICON_BRANDS_AVIANEX                            0x0000F11F
#define FONTAWESOME_ICON_BRANDS_AVIATO                             0x0000F120
#define FONTAWESOME_ICON_BRANDS_AWS                                0x0000F121
#define FONTAWESOME_ICON_BRANDS_BANDCAMP                           0x0000F122
#define FONTAWESOME_ICON_BRANDS_BEHANCE                            0x0000F123
#define FONTAWESOME_ICON_BRANDS_BEHANCE_SQUARE                     0x0000F124
#define FONTAWESOME_ICON_BRANDS_BIMOBJECT                          0x0000F125
#define FONTAWESOME_ICON_BRANDS_BITBUCKET                          0x0000F126
#define FONTAWESOME_ICON_BRANDS_BITCOIN                            0x0000F127
#define FONTAWESOME_ICON_BRANDS_BITY                               0x0000F128
#define FONTAWESOME_ICON_BRANDS_BLACK_TIE                          0x0000F129
#define FONTAWESOME_ICON_BRANDS_BLACKBERRY                         0x0000F12A
#define FONTAWESOME_ICON_BRANDS_BLOGGER                            0x0000F12B
#define FONTAWESOME_ICON_BRANDS_BLOGGER_B                          0x0000F12C
#define FONTAWESOME_ICON_BRANDS_BLUETOOTH                          0x0000F12D
#define FONTAWESOME_ICON_BRANDS_BLUETOOTH_B                        0x0000F12E
#define FONTAWESOME_ICON_BRANDS_BTC                                0x0000F12F
#define FONTAWESOME_ICON_BRANDS_BUROMOBELEXPERTE                   0x0000F130
#define FONTAWESOME_ICON_BRANDS_BUYSELLADS                         0x0000F131
#define FONTAWESOME_ICON_BRANDS_CC_AMAZON_PAY                      0x0000F132
#define FONTAWESOME_ICON_BRANDS_CC_AMEX                            0x0000F133
#define FONTAWESOME_ICON_BRANDS_CC_APPLE_PAY                       0x0000F134
#define FONTAWESOME_ICON_BRANDS_CC_DINERS_CLUB                     0x0000F135
#define FONTAWESOME_ICON_BRANDS_CC_DISCOVER                        0x0000F136
#define FONTAWESOME_ICON_BRANDS_CC_JCB                             0x0000F137
#define FONTAWESOME_ICON_BRANDS_CC_MASTERCARD                      0x0000F138
#define FONTAWESOME_ICON_BRANDS_CC_PAYPAL                          0x0000F139
#define FONTAWESOME_ICON_BRANDS_CC_STRIPE                          0x0000F13A
#define FONTAWESOME_ICON_BRANDS_CC_VISA                            0x0000F13B
#define FONTAWESOME_ICON_BRANDS_CENTERCODE                         0x0000F13C
#define FONTAWESOME_ICON_BRANDS_CHROME                             0x0000F13D
#define FONTAWESOME_ICON_BRANDS_CLOUDSCALE                         0x0000F13E
#define FONTAWESOME_ICON_BRANDS_CLOUDSMITH                         0x0000F13F
#define FONTAWESOME_ICON_BRANDS_CLOUDVERSIFY                       0x0000F140
#define FONTAWESOME_ICON_BRANDS_CODEPEN                            0x0000F141
#define FONTAWESOME_ICON_BRANDS_CODIEPIE                           0x0000F142
#define FONTAWESOME_ICON_BRANDS_CONNECTDEVELOP                     0x0000F143
#define FONTAWESOME_ICON_BRANDS_CONTAO                             0x0000F144
#define FONTAWESOME_ICON_BRANDS_CPANEL                             0x0000F145
#define FONTAWESOME_ICON_BRANDS_CREATIVE_COMMONS                   0x0000F146
#define FONTAWESOME_ICON_BRANDS_CSS3                               0x0000F147
#define FONTAWESOME_ICON_BRANDS_CSS3_ALT                           0x0000F148
#define FONTAWESOME_ICON_BRANDS_CUTTLEFISH                         0x0000F149
#define FONTAWESOME_ICON_BRANDS_D_AND_D                            0x0000F14A
#define FONTAWESOME_ICON_BRANDS_DASHCUBE                           0x0000F14B
#define FONTAWESOME_ICON_BRANDS_DELICIOUS                          0x0000F14C
#define FONTAWESOME_ICON_BRANDS_DEPLOYDOG                          0x0000F14D
#define FONTAWESOME_ICON_BRANDS_DESKPRO                            0x0000F14E
#define FONTAWESOME_ICON_BRANDS_DEVIANTART                         0x0000F14F
#define FONTAWESOME_ICON_BRANDS_DIGG                               0x0000F150
#define FONTAWESOME_ICON_BRANDS_DIGITAL_OCEAN                      0x0000F151
#define FONTAWESOME_ICON_BRANDS_DISCORD                            0x0000F152
#define FONTAWESOME_ICON_BRANDS_DISCOURSE                          0x0000F153
#define FONTAWESOME_ICON_BRANDS_DOCHUB                             0x0000F154
#define FONTAWESOME_ICON_BRANDS_DOCKER                             0x0000F155
#define FONTAWESOME_ICON_BRANDS_DRAFT2DIGITAL                      0x0000F156
#define FONTAWESOME_ICON_BRANDS_DRIBBBLE                           0x0000F157
#define FONTAWESOME_ICON_BRANDS_DRIBBBLE_SQUARE                    0x0000F158
#define FONTAWESOME_ICON_BRANDS_DROPBOX                            0x0000F159
#define FONTAWESOME_ICON_BRANDS_DRUPAL                             0x0000F15A
#define FONTAWESOME_ICON_BRANDS_DYALOG                             0x0000F15B
#define FONTAWESOME_ICON_BRANDS_EARLYBIRDS                         0x0000F15C
#define FONTAWESOME_ICON_BRANDS_EDGE                               0x0000F15D
#define FONTAWESOME_ICON_BRANDS_ELEMENTOR                          0x0000F15E
#define FONTAWESOME_ICON_BRANDS_EMBER                              0x0000F15F
#define FONTAWESOME_ICON_BRANDS_EMPIRE                             0x0000F160
#define FONTAWESOME_ICON_BRANDS_ENVIRA                             0x0000F161
#define FONTAWESOME_ICON_BRANDS_ERLANG                             0x0000F162
#define FONTAWESOME_ICON_BRANDS_ETHEREUM                           0x0000F163
#define FONTAWESOME_ICON_BRANDS_ETSY                               0x0000F164
#define FONTAWESOME_ICON_BRANDS_EXPEDITEDSSL                       0x0000F165
#define FONTAWESOME_ICON_BRANDS_FACEBOOK                           0x0000F166
#define FONTAWESOME_ICON_BRANDS_FACEBOOK_F                         0x0000F167
#define FONTAWESOME_ICON_BRANDS_FACEBOOK_MESSENGER                 0x0000F168
#define FONTAWESOME_ICON_BRANDS_FACEBOOK_SQUARE                    0x0000F169
#define FONTAWESOME_ICON_BRANDS_FIREFOX                            0x0000F16A
#define FONTAWESOME_ICON_BRANDS_FIRST_ORDER                        0x0000F16B
#define FONTAWESOME_ICON_BRANDS_FIRSTDRAFT                         0x0000F16C
#define FONTAWESOME_ICON_BRANDS_FLICKR                             0x0000F16D
#define FONTAWESOME_ICON_BRANDS_FLIPBOARD                          0x0000F16E
#define FONTAWESOME_ICON_BRANDS_FLY                                0x0000F16F
#define FONTAWESOME_ICON_BRANDS_FONT_AWESOME                       0x0000F170
#define FONTAWESOME_ICON_BRANDS_FONT_AWESOME_ALT                   0x0000F171
#define FONTAWESOME_ICON_BRANDS_FONT_AWESOME_FLAG                  0x0000F172
#define FONTAWESOME_ICON_BRANDS_FONTICONS                          0x0000F173
#define FONTAWESOME_ICON_BRANDS_FONTICONS_FI                       0x0000F174
#define FONTAWESOME_ICON_BRANDS_FORT_AWESOME                       0x0000F175
#define FONTAWESOME_ICON_BRANDS_FORT_AWESOME_ALT                   0x0000F176
#define FONTAWESOME_ICON_BRANDS_FORUMBEE                           0x0000F177
#define FONTAWESOME_ICON_BRANDS_FOURSQUARE                         0x0000F178
#define FONTAWESOME_ICON_BRANDS_FREE_CODE_CAMP                     0x0000F179
#define FONTAWESOME_ICON_BRANDS_FREEBSD                            0x0000F17A
#define FONTAWESOME_ICON_BRANDS_GET_POCKET                         0x0000F17B
#define FONTAWESOME_ICON_BRANDS_GG                                 0x0000F17C
#define FONTAWESOME_ICON_BRANDS_GG_CIRCLE                          0x0000F17D
#define FONTAWESOME_ICON_BRANDS_GIT                                0x0000F17E
#define FONTAWESOME_ICON_BRANDS_GIT_SQUARE                         0x0000F17F
#define FONTAWESOME_ICON_BRANDS_GITHUB                             0x0000F180
#define FONTAWESOME_ICON_BRANDS_GITHUB_ALT                         0x0000F181
#define FONTAWESOME_ICON_BRANDS_GITHUB_SQUARE                      0x0000F182
#define FONTAWESOME_ICON_BRANDS_GITKRAKEN                          0x0000F183
#define FONTAWESOME_ICON_BRANDS_GITLAB                             0x0000F184
#define FONTAWESOME_ICON_BRANDS_GITTER                             0x0000F185
#define FONTAWESOME_ICON_BRANDS_GLIDE                              0x0000F186
#define FONTAWESOME_ICON_BRANDS_GLIDE_G                            0x0000F187
#define FONTAWESOME_ICON_BRANDS_GOFORE                             0x0000F188
#define FONTAWESOME_ICON_BRANDS_GOODREADS                          0x0000F189
#define FONTAWESOME_ICON_BRANDS_GOODREADS_G                        0x0000F18A
#define FONTAWESOME_ICON_BRANDS_GOOGLE                             0x0000F18B
#define FONTAWESOME_ICON_BRANDS_GOOGLE_DRIVE                       0x0000F18C
#define FONTAWESOME_ICON_BRANDS_GOOGLE_PLAY                        0x0000F18D
#define FONTAWESOME_ICON_BRANDS_GOOGLE_PLUS                        0x0000F18E
#define FONTAWESOME_ICON_BRANDS_GOOGLE_PLUS_G                      0x0000F18F
#define FONTAWESOME_ICON_BRANDS_GOOGLE_PLUS_SQUARE                 0x0000F190
#define FONTAWESOME_ICON_BRANDS_GOOGLE_WALLET                      0x0000F191
#define FONTAWESOME_ICON_BRANDS_GRATIPAY                           0x0000F192
#define FONTAWESOME_ICON_BRANDS_GRAV                               0x0000F193
#define FONTAWESOME_ICON_BRANDS_GRIPFIRE                           0x0000F194
#define FONTAWESOME_ICON_BRANDS_GRUNT                              0x0000F195
#define FONTAWESOME_ICON_BRANDS_GULP                               0x0000F196
#define FONTAWESOME_ICON_BRANDS_HACKER_NEWS                        0x0000F197
#define FONTAWESOME_ICON_BRANDS_HACKER_NEWS_SQUARE                 0x0000F198
#define FONTAWESOME_ICON_BRANDS_HIPS                               0x0000F199
#define FONTAWESOME_ICON_BRANDS_HIRE_A_HELPER                      0x0000F19A
#define FONTAWESOME_ICON_BRANDS_HOOLI                              0x0000F19B
#define FONTAWESOME_ICON_BRANDS_HOTJAR                             0x0000F19C
#define FONTAWESOME_ICON_BRANDS_HOUZZ                              0x0000F19D
#define FONTAWESOME_ICON_BRANDS_HTML5                              0x0000F19E
#define FONTAWESOME_ICON_BRANDS_HUBSPOT                            0x0000F19F
#define FONTAWESOME_ICON_BRANDS_IMDB                               0x0000F1A0
#define FONTAWESOME_ICON_BRANDS_INSTAGRAM                          0x0000F1A1
#define FONTAWESOME_ICON_BRANDS_INTERNET_EXPLORER                  0x0000F1A2
#define FONTAWESOME_ICON_BRANDS_IOXHOST                            0x0000F1A3
#define FONTAWESOME_ICON_BRANDS_ITUNES                             0x0000F1A4
#define FONTAWESOME_ICON_BRANDS_ITUNES_NOTE                        0x0000F1A5
#define FONTAWESOME_ICON_BRANDS_JENKINS                            0x0000F1A6
#define FONTAWESOME_ICON_BRANDS_JOGET                              0x0000F1A7
#define FONTAWESOME_ICON_BRANDS_JOOMLA                             0x0000F1A8
#define FONTAWESOME_ICON_BRANDS_JS                                 0x0000F1A9
#define FONTAWESOME_ICON_BRANDS_JS_SQUARE                          0x0000F1AA
#define FONTAWESOME_ICON_BRANDS_JSFIDDLE                           0x0000F1AB
#define FONTAWESOME_ICON_BRANDS_KEYCDN                             0x0000F1AC
#define FONTAWESOME_ICON_BRANDS_KICKSTARTER                        0x0000F1AD
#define FONTAWESOME_ICON_BRANDS_KICKSTARTER_K                      0x0000F1AE
#define FONTAWESOME_ICON_BRANDS_KORVUE                             0x0000F1AF
#define FONTAWESOME_ICON_BRANDS_LARAVEL                            0x0000F1B0
#define FONTAWESOME_ICON_BRANDS_LASTFM                             0x0000F1B1
#define FONTAWESOME_ICON_BRANDS_LASTFM_SQUARE                      0x0000F1B2
#define FONTAWESOME_ICON_BRANDS_LEANPUB                            0x0000F1B3
#define FONTAWESOME_ICON_BRANDS_LESS                               0x0000F1B4
#define FONTAWESOME_ICON_BRANDS_LINE                               0x0000F1B5
#define FONTAWESOME_ICON_BRANDS_LINKEDIN                           0x0000F1B6
#define FONTAWESOME_ICON_BRANDS_LINKEDIN_IN                        0x0000F1B7
#define FONTAWESOME_ICON_BRANDS_LINODE                             0x0000F1B8
#define FONTAWESOME_ICON_BRANDS_LINUX                              0x0000F1B9
#define FONTAWESOME_ICON_BRANDS_LYFT                               0x0000F1BA
#define FONTAWESOME_ICON_BRANDS_MAGENTO                            0x0000F1BB
#define FONTAWESOME_ICON_BRANDS_MAXCDN                             0x0000F1BC
#define FONTAWESOME_ICON_BRANDS_MEDAPPS                            0x0000F1BD
#define FONTAWESOME_ICON_BRANDS_MEDIUM                             0x0000F1BE
#define FONTAWESOME_ICON_BRANDS_MEDIUM_M                           0x0000F1BF
#define FONTAWESOME_ICON_BRANDS_MEDRT                              0x0000F1C0
#define FONTAWESOME_ICON_BRANDS_MEETUP                             0x0000F1C1
#define FONTAWESOME_ICON_BRANDS_MICROSOFT                          0x0000F1C2
#define FONTAWESOME_ICON_BRANDS_MIX                                0x0000F1C3
#define FONTAWESOME_ICON_BRANDS_MIXCLOUD                           0x0000F1C4
#define FONTAWESOME_ICON_BRANDS_MIZUNI                             0x0000F1C5
#define FONTAWESOME_ICON_BRANDS_MODX                               0x0000F1C6
#define FONTAWESOME_ICON_BRANDS_MONERO                             0x0000F1C7
#define FONTAWESOME_ICON_BRANDS_NAPSTER                            0x0000F1C8
#define FONTAWESOME_ICON_BRANDS_NINTENDO_SWITCH                    0x0000F1C9
#define FONTAWESOME_ICON_BRANDS_NODE                               0x0000F1CA
#define FONTAWESOME_ICON_BRANDS_NODE_JS                            0x0000F1CB
#define FONTAWESOME_ICON_BRANDS_NPM                                0x0000F1CC
#define FONTAWESOME_ICON_BRANDS_NS8                                0x0000F1CD
#define FONTAWESOME_ICON_BRANDS_NUTRITIONIX                        0x0000F1CE
#define FONTAWESOME_ICON_BRANDS_ODNOKLASSNIKI                      0x0000F1CF
#define FONTAWESOME_ICON_BRANDS_ODNOKLASSNIKI_SQUARE               0x0000F1D0
#define FONTAWESOME_ICON_BRANDS_OPENCART                           0x0000F1D1
#define FONTAWESOME_ICON_BRANDS_OPENID                             0x0000F1D2
#define FONTAWESOME_ICON_BRANDS_OPERA                              0x0000F1D3
#define FONTAWESOME_ICON_BRANDS_OPTIN_MONSTER                      0x0000F1D4
#define FONTAWESOME_ICON_BRANDS_OSI                                0x0000F1D5
#define FONTAWESOME_ICON_BRANDS_PAGE4                              0x0000F1D6
#define FONTAWESOME_ICON_BRANDS_PAGELINES                          0x0000F1D7
#define FONTAWESOME_ICON_BRANDS_PALFED                             0x0000F1D8
#define FONTAWESOME_ICON_BRANDS_PATREON                            0x0000F1D9
#define FONTAWESOME_ICON_BRANDS_PAYPAL                             0x0000F1DA
#define FONTAWESOME_ICON_BRANDS_PERISCOPE                          0x0000F1DB
#define FONTAWESOME_ICON_BRANDS_PHABRICATOR                        0x0000F1DC
#define FONTAWESOME_ICON_BRANDS_PHOENIX_FRAMEWORK                  0x0000F1DD
#define FONTAWESOME_ICON_BRANDS_PHP                                0x0000F1DE
#define FONTAWESOME_ICON_BRANDS_PIED_PIPER                         0x0000F1DF
#define FONTAWESOME_ICON_BRANDS_PIED_PIPER_ALT                     0x0000F1E0
#define FONTAWESOME_ICON_BRANDS_PIED_PIPER_PP                      0x0000F1E1
#define FONTAWESOME_ICON_BRANDS_PINTEREST                          0x0000F1E2
#define FONTAWESOME_ICON_BRANDS_PINTEREST_P                        0x0000F1E3
#define FONTAWESOME_ICON_BRANDS_PINTEREST_SQUARE                   0x0000F1E4
#define FONTAWESOME_ICON_BRANDS_PLAYSTATION                        0x0000F1E5
#define FONTAWESOME_ICON_BRANDS_PRODUCT_HUNT                       0x0000F1E6
#define FONTAWESOME_ICON_BRANDS_PUSHED                             0x0000F1E7
#define FONTAWESOME_ICON_BRANDS_PYTHON                             0x0000F1E8
#define FONTAWESOME_ICON_BRANDS_QQ                                 0x0000F1E9
#define FONTAWESOME_ICON_BRANDS_QUINSCAPE                          0x0000F1EA
#define FONTAWESOME_ICON_BRANDS_QUORA                              0x0000F1EB
#define FONTAWESOME_ICON_BRANDS_RAVELRY                            0x0000F1EC
#define FONTAWESOME_ICON_BRANDS_REACT                              0x0000F1ED
#define FONTAWESOME_ICON_BRANDS_REBEL                              0x0000F1EE
#define FONTAWESOME_ICON_BRANDS_RED_RIVER                          0x0000F1EF
#define FONTAWESOME_ICON_BRANDS_REDDIT                             0x0000F1F0
#define FONTAWESOME_ICON_BRANDS_REDDIT_ALIEN                       0x0000F1F1
#define FONTAWESOME_ICON_BRANDS_REDDIT_SQUARE                      0x0000F1F2
#define FONTAWESOME_ICON_BRANDS_RENDACT                            0x0000F1F3
#define FONTAWESOME_ICON_BRANDS_RENREN                             0x0000F1F4
#define FONTAWESOME_ICON_BRANDS_REPLYD                             0x0000F1F5
#define FONTAWESOME_ICON_BRANDS_RESOLVING                          0x0000F1F6
#define FONTAWESOME_ICON_BRANDS_ROCKETCHAT                         0x0000F1F7
#define FONTAWESOME_ICON_BRANDS_ROCKRMS                            0x0000F1F8
#define FONTAWESOME_ICON_BRANDS_SAFARI                             0x0000F1F9
#define FONTAWESOME_ICON_BRANDS_SASS                               0x0000F1FA
#define FONTAWESOME_ICON_BRANDS_SCHLIX                             0x0000F1FB
#define FONTAWESOME_ICON_BRANDS_SCRIBD                             0x0000F1FC
#define FONTAWESOME_ICON_BRANDS_SEARCHENGIN                        0x0000F1FD
#define FONTAWESOME_ICON_BRANDS_SELLCAST                           0x0000F1FE
#define FONTAWESOME_ICON_BRANDS_SELLSY                             0x0000F1FF
#define FONTAWESOME_ICON_BRANDS_SERVICESTACK                       0x0000F200
#define FONTAWESOME_ICON_BRANDS_SHIRTSINBULK                       0x0000F201
#define FONTAWESOME_ICON_BRANDS_SIMPLYBUILT                        0x0000F202
#define FONTAWESOME_ICON_BRANDS_SISTRIX                            0x0000F203
#define FONTAWESOME_ICON_BRANDS_SKYATLAS                           0x0000F204
#define FONTAWESOME_ICON_BRANDS_SKYPE                              0x0000F205
#define FONTAWESOME_ICON_BRANDS_SLACK                              0x0000F206
#define FONTAWESOME_ICON_BRANDS_SLACK_HASH                         0x0000F207
#define FONTAWESOME_ICON_BRANDS_SLIDESHARE                         0x0000F208
#define FONTAWESOME_ICON_BRANDS_SNAPCHAT                           0x0000F209
#define FONTAWESOME_ICON_BRANDS_SNAPCHAT_GHOST                     0x0000F20A
#define FONTAWESOME_ICON_BRANDS_SNAPCHAT_SQUARE                    0x0000F20B
#define FONTAWESOME_ICON_BRANDS_SOUNDCLOUD                         0x0000F20C
#define FONTAWESOME_ICON_BRANDS_SPEAKAP                            0x0000F20D
#define FONTAWESOME_ICON_BRANDS_SPOTIFY                            0x0000F20E
#define FONTAWESOME_ICON_BRANDS_STACK_EXCHANGE                     0x0000F20F
#define FONTAWESOME_ICON_BRANDS_STACK_OVERFLOW                     0x0000F210
#define FONTAWESOME_ICON_BRANDS_STAYLINKED                         0x0000F211
#define FONTAWESOME_ICON_BRANDS_STEAM                              0x0000F212
#define FONTAWESOME_ICON_BRANDS_STEAM_SQUARE                       0x0000F213
#define FONTAWESOME_ICON_BRANDS_STEAM_SYMBOL                       0x0000F214
#define FONTAWESOME_ICON_BRANDS_STICKER_MULE                       0x0000F215
#define FONTAWESOME_ICON_BRANDS_STRAVA                             0x0000F216
#define FONTAWESOME_ICON_BRANDS_STRIPE                             0x0000F217
#define FONTAWESOME_ICON_BRANDS_STRIPE_S                           0x0000F218
#define FONTAWESOME_ICON_BRANDS_STUDIOVINARI                       0x0000F219
#define FONTAWESOME_ICON_BRANDS_STUMBLEUPON                        0x0000F21A
#define FONTAWESOME_ICON_BRANDS_STUMBLEUPON_CIRCLE                 0x0000F21B
#define FONTAWESOME_ICON_BRANDS_SUPERPOWERS                        0x0000F21C
#define FONTAWESOME_ICON_BRANDS_SUPPLE                             0x0000F21D
#define FONTAWESOME_ICON_BRANDS_TELEGRAM                           0x0000F21E
#define FONTAWESOME_ICON_BRANDS_TELEGRAM_PLANE                     0x0000F21F
#define FONTAWESOME_ICON_BRANDS_TENCENT_WEIBO                      0x0000F220
#define FONTAWESOME_ICON_BRANDS_THEMEISLE                          0x0000F221
#define FONTAWESOME_ICON_BRANDS_TRELLO                             0x0000F222
#define FONTAWESOME_ICON_BRANDS_TRIPADVISOR                        0x0000F223
#define FONTAWESOME_ICON_BRANDS_TUMBLR                             0x0000F224
#define FONTAWESOME_ICON_BRANDS_TUMBLR_SQUARE                      0x0000F225
#define FONTAWESOME_ICON_BRANDS_TWITCH                             0x0000F226
#define FONTAWESOME_ICON_BRANDS_TWITTER                            0x0000F227
#define FONTAWESOME_ICON_BRANDS_TWITTER_SQUARE                     0x0000F228
#define FONTAWESOME_ICON_BRANDS_TYPO3                              0x0000F229
#define FONTAWESOME_ICON_BRANDS_UBER                               0x0000F22A
#define FONTAWESOME_ICON_BRANDS_UIKIT                              0x0000F22B
#define FONTAWESOME_ICON_BRANDS_UNIREGISTRY                        0x0000F22C
#define FONTAWESOME_ICON_BRANDS_UNTAPPD                            0x0000F22D
#define FONTAWESOME_ICON_BRANDS_USB                                0x0000F22E
#define FONTAWESOME_ICON_BRANDS_USSUNNAH                           0x0000F22F
#define FONTAWESOME_ICON_BRANDS_VAADIN                             0x0000F230
#define FONTAWESOME_ICON_BRANDS_VIACOIN                            0x0000F231
#define FONTAWESOME_ICON_BRANDS_VIADEO                             0x0000F232
#define FONTAWESOME_ICON_BRANDS_VIADEO_SQUARE                      0x0000F233
#define FONTAWESOME_ICON_BRANDS_VIBER                              0x0000F234
#define FONTAWESOME_ICON_BRANDS_VIMEO                              0x0000F235
#define FONTAWESOME_ICON_BRANDS_VIMEO_SQUARE                       0x0000F236
#define FONTAWESOME_ICON_BRANDS_VIMEO_V                            0x0000F237
#define FONTAWESOME_ICON_BRANDS_VINE                               0x0000F238
#define FONTAWESOME_ICON_BRANDS_VK                                 0x0000F239
#define FONTAWESOME_ICON_BRANDS_VNV                                0x0000F23A
#define FONTAWESOME_ICON_BRANDS_VUEJS                              0x0000F23B
#define FONTAWESOME_ICON_BRANDS_WEIBO                              0x0000F23C
#define FONTAWESOME_ICON_BRANDS_WEIXIN                             0x0000F23D
#define FONTAWESOME_ICON_BRANDS_WHATSAPP                           0x0000F23E
#define FONTAWESOME_ICON_BRANDS_WHATSAPP_SQUARE                    0x0000F23F
#define FONTAWESOME_ICON_BRANDS_WHMCS                              0x0000F240
#define FONTAWESOME_ICON_BRANDS_WIKIPEDIA_W                        0x0000F241
#define FONTAWESOME_ICON_BRANDS_WINDOWS                            0x0000F242
#define FONTAWESOME_ICON_BRANDS_WORDPRESS                          0x0000F243
#define FONTAWESOME_ICON_BRANDS_WORDPRESS_SIMPLE                   0x0000F244
#define FONTAWESOME_ICON_BRANDS_WPBEGINNER                         0x0000F245
#define FONTAWESOME_ICON_BRANDS_WPEXPLORER                         0x0000F246
#define FONTAWESOME_ICON_BRANDS_WPFORMS                            0x0000F247
#define FONTAWESOME_ICON_BRANDS_XBOX                               0x0000F248
#define FONTAWESOME_ICON_BRANDS_XING                               0x0000F249
#define FONTAWESOME_ICON_BRANDS_XING_SQUARE                        0x0000F24A
#define FONTAWESOME_ICON_BRANDS_Y_COMBINATOR                       0x0000F24B
#define FONTAWESOME_ICON_BRANDS_YAHOO                              0x0000F24C
#define FONTAWESOME_ICON_BRANDS_YANDEX                             0x0000F24D
#define FONTAWESOME_ICON_BRANDS_YANDEX_INTERNATIONAL               0x0000F24E
#define FONTAWESOME_ICON_BRANDS_YELP                               0x0000F24F
#define FONTAWESOME_ICON_BRANDS_YOAST                              0x0000F250
#define FONTAWESOME_ICON_BRANDS_YOUTUBE                            0x0000F251
#define FONTAWESOME_ICON_BRANDS_YOUTUBE_SQUARE                     0x0000F252
#define FONTAWESOME_ICON_BUILDING                                  0x0000F253
#define FONTAWESOME_ICON_CALENDAR                                  0x0000F254
#define FONTAWESOME_ICON_CALENDAR_ALT                              0x0000F255
#define FONTAWESOME_ICON_CALENDAR_CHECK                            0x0000F256
#define FONTAWESOME_ICON_CALENDAR_MINUS                            0x0000F257
#define FONTAWESOME_ICON_CALENDAR_PLUS                             0x0000F258
#define FONTAWESOME_ICON_CALENDAR_TIMES                            0x0000F259
#define FONTAWESOME_ICON_CARET_SQUARE_DOWN                         0x0000F25A
#define FONTAWESOME_ICON_CARET_SQUARE_LEFT                         0x0000F25B
#define FONTAWESOME_ICON_CARET_SQUARE_RIGHT                        0x0000F25C
#define FONTAWESOME_ICON_CARET_SQUARE_UP                           0x0000F25D
#define FONTAWESOME_ICON_CHART_BAR                                 0x0000F25E
#define FONTAWESOME_ICON_CHECK_CIRCLE                              0x0000F25F
#define FONTAWESOME_ICON_CHECK_SQUARE                              0x0000F260
#define FONTAWESOME_ICON_CIRCLE                                    0x0000F261
#define FONTAWESOME_ICON_CLIPBOARD                                 0x0000F262
#define FONTAWESOME_ICON_CLOCK                                     0x0000F263
#define FONTAWESOME_ICON_CLONE                                     0x0000F264
#define FONTAWESOME_ICON_CLOSED_CAPTIONING                         0x0000F265
#define FONTAWESOME_ICON_COMMENT                                   0x0000F266
#define FONTAWESOME_ICON_COMMENT_ALT                               0x0000F267
#define FONTAWESOME_ICON_COMMENTS                                  0x0000F268
#define FONTAWESOME_ICON_COMPASS                                   0x0000F269
#define FONTAWESOME_ICON_COPY                                      0x0000F26A
#define FONTAWESOME_ICON_COPYRIGHT                                 0x0000F26B
#define FONTAWESOME_ICON_CREDIT_CARD                               0x0000F26C
#define FONTAWESOME_ICON_DOT_CIRCLE                                0x0000F26D
#define FONTAWESOME_ICON_EDIT                                      0x0000F26E
#define FONTAWESOME_ICON_ENVELOPE                                  0x0000F26F
#define FONTAWESOME_ICON_ENVELOPE_OPEN                             0x0000F270
#define FONTAWESOME_ICON_EYE_SLASH                                 0x0000F271
#define FONTAWESOME_ICON_FILE                                      0x0000F272
#define FONTAWESOME_ICON_FILE_ALT                                  0x0000F273
#define FONTAWESOME_ICON_FILE_ARCHIVE                              0x0000F274
#define FONTAWESOME_ICON_FILE_AUDIO                                0x0000F275
#define FONTAWESOME_ICON_FILE_CODE                                 0x0000F276
#define FONTAWESOME_ICON_FILE_EXCEL                                0x0000F277
#define FONTAWESOME_ICON_FILE_IMAGE                                0x0000F278
#define FONTAWESOME_ICON_FILE_PDF                                  0x0000F279
#define FONTAWESOME_ICON_FILE_POWERPOINT                           0x0000F27A
#define FONTAWESOME_ICON_FILE_VIDEO                                0x0000F27B
#define FONTAWESOME_ICON_FILE_WORD                                 0x0000F27C
#define FONTAWESOME_ICON_FLAG                                      0x0000F27D
#define FONTAWESOME_ICON_FOLDER                                    0x0000F27E
#define FONTAWESOME_ICON_FOLDER_OPEN                               0x0000F27F
#define FONTAWESOME_ICON_FROWN                                     0x0000F280
#define FONTAWESOME_ICON_FUTBOL                                    0x0000F281
#define FONTAWESOME_ICON_GEM                                       0x0000F282
#define FONTAWESOME_ICON_HAND_LIZARD                               0x0000F283
#define FONTAWESOME_ICON_HAND_PAPER                                0x0000F284
#define FONTAWESOME_ICON_HAND_PEACE                                0x0000F285
#define FONTAWESOME_ICON_HAND_POINT_DOWN                           0x0000F286
#define FONTAWESOME_ICON_HAND_POINT_LEFT                           0x0000F287
#define FONTAWESOME_ICON_HAND_POINT_RIGHT                          0x0000F288
#define FONTAWESOME_ICON_HAND_POINT_UP                             0x0000F289
#define FONTAWESOME_ICON_HAND_POINTER                              0x0000F28A
#define FONTAWESOME_ICON_HAND_ROCK                                 0x0000F28B
#define FONTAWESOME_ICON_HAND_SCISSORS                             0x0000F28C
#define FONTAWESOME_ICON_HAND_SPOCK                                0x0000F28D
#define FONTAWESOME_ICON_HANDSHAKE                                 0x0000F28E
#define FONTAWESOME_ICON_HDD                                       0x0000F28F
#define FONTAWESOME_ICON_HEART                                     0x0000F290
#define FONTAWESOME_ICON_HOSPITAL                                  0x0000F291
#define FONTAWESOME_ICON_HOURGLASS                                 0x0000F292
#define FONTAWESOME_ICON_ID_BADGE                                  0x0000F293
#define FONTAWESOME_ICON_ID_CARD                                   0x0000F294
#define FONTAWESOME_ICON_IMAGE                                     0x0000F295
#define FONTAWESOME_ICON_IMAGES                                    0x0000F296
#define FONTAWESOME_ICON_KEYBOARD                                  0x0000F297
#define FONTAWESOME_ICON_LEMON                                     0x0000F298
#define FONTAWESOME_ICON_LIFE_RING                                 0x0000F299
#define FONTAWESOME_ICON_LIGHTBULB                                 0x0000F29A
#define FONTAWESOME_ICON_LIST_ALT                                  0x0000F29B
#define FONTAWESOME_ICON_MAP                                       0x0000F29C
#define FONTAWESOME_ICON_MEH                                       0x0000F29D
#define FONTAWESOME_ICON_MINUS_SQUARE                              0x0000F29E
#define FONTAWESOME_ICON_MONEY_BILL_ALT                            0x0000F29F
#define FONTAWESOME_ICON_MOON                                      0x0000F2A0
#define FONTAWESOME_ICON_NEWSPAPER                                 0x0000F2A1
#define FONTAWESOME_ICON_OBJECT_GROUP                              0x0000F2A2
#define FONTAWESOME_ICON_OBJECT_UNGROUP                            0x0000F2A3
#define FONTAWESOME_ICON_PAPER_PLANE                               0x0000F2A4
#define FONTAWESOME_ICON_PAUSE_CIRCLE                              0x0000F2A5
#define FONTAWESOME_ICON_PLAY_CIRCLE                               0x0000F2A6
#define FONTAWESOME_ICON_PLUS_SQUARE                               0x0000F2A7
#define FONTAWESOME_ICON_QUESTION_CIRCLE                           0x0000F2A8
#define FONTAWESOME_ICON_REGISTERED                                0x0000F2A9
#define FONTAWESOME_ICON_SAVE                                      0x0000F2AA
#define FONTAWESOME_ICON_SHARE_SQUARE                              0x0000F2AB
#define FONTAWESOME_ICON_SMILE                                     0x0000F2AC
#define FONTAWESOME_ICON_SNOWFLAKE                                 0x0000F2AD
#define FONTAWESOME_ICON_SOLID_ADDRESS_BOOK                        0x0000F2AE
#define FONTAWESOME_ICON_SOLID_ADDRESS_CARD                        0x0000F2AF
#define FONTAWESOME_ICON_SOLID_ADJUST                              0x0000F2B0
#define FONTAWESOME_ICON_SOLID_ALIGN_CENTER                        0x0000F2B1
#define FONTAWESOME_ICON_SOLID_ALIGN_JUSTIFY                       0x0000F2B2
#define FONTAWESOME_ICON_SOLID_ALIGN_LEFT                          0x0000F2B3
#define FONTAWESOME_ICON_SOLID_ALIGN_RIGHT                         0x0000F2B4
#define FONTAWESOME_ICON_SOLID_AMBULANCE                           0x0000F2B5
#define FONTAWESOME_ICON_SOLID_AMERICAN_SIGN_LANGUAGE_INTERPRETING 0x0000F2B6
#define FONTAWESOME_ICON_SOLID_ANCHOR                              0x0000F2B7
#define FONTAWESOME_ICON_SOLID_ANGLE_DOUBLE_DOWN                   0x0000F2B8
#define FONTAWESOME_ICON_SOLID_ANGLE_DOUBLE_LEFT                   0x0000F2B9
#define FONTAWESOME_ICON_SOLID_ANGLE_DOUBLE_RIGHT                  0x0000F2BA
#define FONTAWESOME_ICON_SOLID_ANGLE_DOUBLE_UP                     0x0000F2BB
#define FONTAWESOME_ICON_SOLID_ANGLE_DOWN                          0x0000F2BC
#define FONTAWESOME_ICON_SOLID_ANGLE_LEFT                          0x0000F2BD
#define FONTAWESOME_ICON_SOLID_ANGLE_RIGHT                         0x0000F2BE
#define FONTAWESOME_ICON_SOLID_ANGLE_UP                            0x0000F2BF
#define FONTAWESOME_ICON_SOLID_ARCHIVE                             0x0000F2C0
#define FONTAWESOME_ICON_SOLID_ARROW_ALT_CIRCLE_DOWN               0x0000F2C1
#define FONTAWESOME_ICON_SOLID_ARROW_ALT_CIRCLE_LEFT               0x0000F2C2
#define FONTAWESOME_ICON_SOLID_ARROW_ALT_CIRCLE_RIGHT              0x0000F2C3
#define FONTAWESOME_ICON_SOLID_ARROW_ALT_CIRCLE_UP                 0x0000F2C4
#define FONTAWESOME_ICON_SOLID_ARROW_CIRCLE_DOWN                   0x0000F2C5
#define FONTAWESOME_ICON_SOLID_ARROW_CIRCLE_LEFT                   0x0000F2C6
#define FONTAWESOME_ICON_SOLID_ARROW_CIRCLE_RIGHT                  0x0000F2C7
#define FONTAWESOME_ICON_SOLID_ARROW_CIRCLE_UP                     0x0000F2C8
#define FONTAWESOME_ICON_SOLID_ARROW_DOWN                          0x0000F2C9
#define FONTAWESOME_ICON_SOLID_ARROW_LEFT                          0x0000F2CA
#define FONTAWESOME_ICON_SOLID_ARROW_RIGHT                         0x0000F2CB
#define FONTAWESOME_ICON_SOLID_ARROW_UP                            0x0000F2CC
#define FONTAWESOME_ICON_SOLID_ARROWS_ALT                          0x0000F2CD
#define FONTAWESOME_ICON_SOLID_ARROWS_ALT_H                        0x0000F2CE
#define FONTAWESOME_ICON_SOLID_ARROWS_ALT_V                        0x0000F2CF
#define FONTAWESOME_ICON_SOLID_ASSISTIVE_LISTENING_SYSTEMS         0x0000F2D0
#define FONTAWESOME_ICON_SOLID_ASTERISK                            0x0000F2D1
#define FONTAWESOME_ICON_SOLID_AT                                  0x0000F2D2
#define FONTAWESOME_ICON_SOLID_AUDIO_DESCRIPTION                   0x0000F2D3
#define FONTAWESOME_ICON_SOLID_BACKWARD                            0x0000F2D4
#define FONTAWESOME_ICON_SOLID_BALANCE_SCALE                       0x0000F2D5
#define FONTAWESOME_ICON_SOLID_BAN                                 0x0000F2D6
#define FONTAWESOME_ICON_SOLID_BARCODE                             0x0000F2D7
#define FONTAWESOME_ICON_SOLID_BARS                                0x0000F2D8
#define FONTAWESOME_ICON_SOLID_BASEBALL_BALL                       0x0000F2D9
#define FONTAWESOME_ICON_SOLID_BASKETBALL_BALL                     0x0000F2DA
#define FONTAWESOME_ICON_SOLID_BATH                                0x0000F2DB
#define FONTAWESOME_ICON_SOLID_BATTERY_EMPTY                       0x0000F2DC
#define FONTAWESOME_ICON_SOLID_BATTERY_FULL                        0x0000F2DD
#define FONTAWESOME_ICON_SOLID_BATTERY_HALF                        0x0000F2DE
#define FONTAWESOME_ICON_SOLID_BATTERY_QUARTER                     0x0000F2DF
#define FONTAWESOME_ICON_SOLID_BATTERY_THREE_QUARTERS              0x0000F2E0
#define FONTAWESOME_ICON_SOLID_BED                                 0x0000F2E1
#define FONTAWESOME_ICON_SOLID_BEER                                0x0000F2E2
#define FONTAWESOME_ICON_SOLID_BELL                                0x0000F2E3
#define FONTAWESOME_ICON_SOLID_BELL_SLASH                          0x0000F2E4
#define FONTAWESOME_ICON_SOLID_BICYCLE                             0x0000F2E5
#define FONTAWESOME_ICON_SOLID_BINOCULARS                          0x0000F2E6
#define FONTAWESOME_ICON_SOLID_BIRTHDAY_CAKE                       0x0000F2E7
#define FONTAWESOME_ICON_SOLID_BLIND                               0x0000F2E8
#define FONTAWESOME_ICON_SOLID_BOLD                                0x0000F2E9
#define FONTAWESOME_ICON_SOLID_BOLT                                0x0000F2EA
#define FONTAWESOME_ICON_SOLID_BOMB                                0x0000F2EB
#define FONTAWESOME_ICON_SOLID_BOOK                                0x0000F2EC
#define FONTAWESOME_ICON_SOLID_BOOKMARK                            0x0000F2ED
#define FONTAWESOME_ICON_SOLID_BOWLING_BALL                        0x0000F2EE
#define FONTAWESOME_ICON_SOLID_BRAILLE                             0x0000F2EF
#define FONTAWESOME_ICON_SOLID_BRIEFCASE                           0x0000F2F0
#define FONTAWESOME_ICON_SOLID_BUG                                 0x0000F2F1
#define FONTAWESOME_ICON_SOLID_BUILDING                            0x0000F2F2
#define FONTAWESOME_ICON_SOLID_BULLHORN                            0x0000F2F3
#define FONTAWESOME_ICON_SOLID_BULLSEYE                            0x0000F2F4
#define FONTAWESOME_ICON_SOLID_BUS                                 0x0000F2F5
#define FONTAWESOME_ICON_SOLID_CALCULATOR                          0x0000F2F6
#define FONTAWESOME_ICON_SOLID_CALENDAR                            0x0000F2F7
#define FONTAWESOME_ICON_SOLID_CALENDAR_ALT                        0x0000F2F8
#define FONTAWESOME_ICON_SOLID_CALENDAR_CHECK                      0x0000F2F9
#define FONTAWESOME_ICON_SOLID_CALENDAR_MINUS                      0x0000F2FA
#define FONTAWESOME_ICON_SOLID_CALENDAR_PLUS                       0x0000F2FB
#define FONTAWESOME_ICON_SOLID_CALENDAR_TIMES                      0x0000F2FC
#define FONTAWESOME_ICON_SOLID_CAMERA                              0x0000F2FD
#define FONTAWESOME_ICON_SOLID_CAMERA_RETRO                        0x0000F2FE
#define FONTAWESOME_ICON_SOLID_CAR                                 0x0000F2FF
#define FONTAWESOME_ICON_SOLID_CARET_DOWN                          0x0000F300
#define FONTAWESOME_ICON_SOLID_CARET_LEFT                          0x0000F301
#define FONTAWESOME_ICON_SOLID_CARET_RIGHT                         0x0000F302
#define FONTAWESOME_ICON_SOLID_CARET_SQUARE_DOWN                   0x0000F303
#define FONTAWESOME_ICON_SOLID_CARET_SQUARE_LEFT                   0x0000F304
#define FONTAWESOME_ICON_SOLID_CARET_SQUARE_RIGHT                  0x0000F305
#define FONTAWESOME_ICON_SOLID_CARET_SQUARE_UP                     0x0000F306
#define FONTAWESOME_ICON_SOLID_CARET_UP                            0x0000F307
#define FONTAWESOME_ICON_SOLID_CART_ARROW_DOWN                     0x0000F308
#define FONTAWESOME_ICON_SOLID_CART_PLUS                           0x0000F309
#define FONTAWESOME_ICON_SOLID_CERTIFICATE                         0x0000F30A
#define FONTAWESOME_ICON_SOLID_CHART_AREA                          0x0000F30B
#define FONTAWESOME_ICON_SOLID_CHART_BAR                           0x0000F30C
#define FONTAWESOME_ICON_SOLID_CHART_LINE                          0x0000F30D
#define FONTAWESOME_ICON_SOLID_CHART_PIE                           0x0000F30E
#define FONTAWESOME_ICON_SOLID_CHECK                               0x0000F30F
#define FONTAWESOME_ICON_SOLID_CHECK_CIRCLE                        0x0000F310
#define FONTAWESOME_ICON_SOLID_CHECK_SQUARE                        0x0000F311
#define FONTAWESOME_ICON_SOLID_CHESS                               0x0000F312
#define FONTAWESOME_ICON_SOLID_CHESS_BISHOP                        0x0000F313
#define FONTAWESOME_ICON_SOLID_CHESS_BOARD                         0x0000F314
#define FONTAWESOME_ICON_SOLID_CHESS_KING                          0x0000F315
#define FONTAWESOME_ICON_SOLID_CHESS_KNIGHT                        0x0000F316
#define FONTAWESOME_ICON_SOLID_CHESS_PAWN                          0x0000F317
#define FONTAWESOME_ICON_SOLID_CHESS_QUEEN                         0x0000F318
#define FONTAWESOME_ICON_SOLID_CHESS_ROOK                          0x0000F319
#define FONTAWESOME_ICON_SOLID_CHEVRON_CIRCLE_DOWN                 0x0000F31A
#define FONTAWESOME_ICON_SOLID_CHEVRON_CIRCLE_LEFT                 0x0000F31B
#define FONTAWESOME_ICON_SOLID_CHEVRON_CIRCLE_RIGHT                0x0000F31C
#define FONTAWESOME_ICON_SOLID_CHEVRON_CIRCLE_UP                   0x0000F31D
#define FONTAWESOME_ICON_SOLID_CHEVRON_DOWN                        0x0000F31E
#define FONTAWESOME_ICON_SOLID_CHEVRON_LEFT                        0x0000F31F
#define FONTAWESOME_ICON_SOLID_CHEVRON_RIGHT                       0x0000F320
#define FONTAWESOME_ICON_SOLID_CHEVRON_UP                          0x0000F321
#define FONTAWESOME_ICON_SOLID_CHILD                               0x0000F322
#define FONTAWESOME_ICON_SOLID_CIRCLE                              0x0000F323
#define FONTAWESOME_ICON_SOLID_CIRCLE_NOTCH                        0x0000F324
#define FONTAWESOME_ICON_SOLID_CLIPBOARD                           0x0000F325
#define FONTAWESOME_ICON_SOLID_CLOCK                               0x0000F326
#define FONTAWESOME_ICON_SOLID_CLONE                               0x0000F327
#define FONTAWESOME_ICON_SOLID_CLOSED_CAPTIONING                   0x0000F328
#define FONTAWESOME_ICON_SOLID_CLOUD                               0x0000F329
#define FONTAWESOME_ICON_SOLID_CLOUD_DOWNLOAD_ALT                  0x0000F32A
#define FONTAWESOME_ICON_SOLID_CLOUD_UPLOAD_ALT                    0x0000F32B
#define FONTAWESOME_ICON_SOLID_CODE                                0x0000F32C
#define FONTAWESOME_ICON_SOLID_CODE_BRANCH                         0x0000F32D
#define FONTAWESOME_ICON_SOLID_COFFEE                              0x0000F32E
#define FONTAWESOME_ICON_SOLID_COG                                 0x0000F32F
#define FONTAWESOME_ICON_SOLID_COGS                                0x0000F330
#define FONTAWESOME_ICON_SOLID_COLUMNS                             0x0000F331
#define FONTAWESOME_ICON_SOLID_COMMENT                             0x0000F332
#define FONTAWESOME_ICON_SOLID_COMMENT_ALT                         0x0000F333
#define FONTAWESOME_ICON_SOLID_COMMENTS                            0x0000F334
#define FONTAWESOME_ICON_SOLID_COMPASS                             0x0000F335
#define FONTAWESOME_ICON_SOLID_COMPRESS                            0x0000F336
#define FONTAWESOME_ICON_SOLID_COPY                                0x0000F337
#define FONTAWESOME_ICON_SOLID_COPYRIGHT                           0x0000F338
#define FONTAWESOME_ICON_SOLID_CREDIT_CARD                         0x0000F339
#define FONTAWESOME_ICON_SOLID_CROP                                0x0000F33A
#define FONTAWESOME_ICON_SOLID_CROSSHAIRS                          0x0000F33B
#define FONTAWESOME_ICON_SOLID_CUBE                                0x0000F33C
#define FONTAWESOME_ICON_SOLID_CUBES                               0x0000F33D
#define FONTAWESOME_ICON_SOLID_CUT                                 0x0000F33E
#define FONTAWESOME_ICON_SOLID_DATABASE                            0x0000F33F
#define FONTAWESOME_ICON_SOLID_DEAF                                0x0000F340
#define FONTAWESOME_ICON_SOLID_DESKTOP                             0x0000F341
#define FONTAWESOME_ICON_SOLID_DOLLAR_SIGN                         0x0000F342
#define FONTAWESOME_ICON_SOLID_DOT_CIRCLE                          0x0000F343
#define FONTAWESOME_ICON_SOLID_DOWNLOAD                            0x0000F344
#define FONTAWESOME_ICON_SOLID_EDIT                                0x0000F345
#define FONTAWESOME_ICON_SOLID_EJECT                               0x0000F346
#define FONTAWESOME_ICON_SOLID_ELLIPSIS_H                          0x0000F347
#define FONTAWESOME_ICON_SOLID_ELLIPSIS_V                          0x0000F348
#define FONTAWESOME_ICON_SOLID_ENVELOPE                            0x0000F349
#define FONTAWESOME_ICON_SOLID_ENVELOPE_OPEN                       0x0000F34A
#define FONTAWESOME_ICON_SOLID_ENVELOPE_SQUARE                     0x0000F34B
#define FONTAWESOME_ICON_SOLID_ERASER                              0x0000F34C
#define FONTAWESOME_ICON_SOLID_EURO_SIGN                           0x0000F34D
#define FONTAWESOME_ICON_SOLID_EXCHANGE_ALT                        0x0000F34E
#define FONTAWESOME_ICON_SOLID_EXCLAMATION                         0x0000F34F
#define FONTAWESOME_ICON_SOLID_EXCLAMATION_CIRCLE                  0x0000F350
#define FONTAWESOME_ICON_SOLID_EXCLAMATION_TRIANGLE                0x0000F351
#define FONTAWESOME_ICON_SOLID_EXPAND                              0x0000F352
#define FONTAWESOME_ICON_SOLID_EXPAND_ARROWS_ALT                   0x0000F353
#define FONTAWESOME_ICON_SOLID_EXTERNAL_LINK_ALT                   0x0000F354
#define FONTAWESOME_ICON_SOLID_EXTERNAL_LINK_SQUARE_ALT            0x0000F355
#define FONTAWESOME_ICON_SOLID_EYE                                 0x0000F356
#define FONTAWESOME_ICON_SOLID_EYE_DROPPER                         0x0000F357
#define FONTAWESOME_ICON_SOLID_EYE_SLASH                           0x0000F358
#define FONTAWESOME_ICON_SOLID_FAST_BACKWARD                       0x0000F359
#define FONTAWESOME_ICON_SOLID_FAST_FORWARD                        0x0000F35A
#define FONTAWESOME_ICON_SOLID_FAX                                 0x0000F35B
#define FONTAWESOME_ICON_SOLID_FEMALE                              0x0000F35C
#define FONTAWESOME_ICON_SOLID_FIGHTER_JET                         0x0000F35D
#define FONTAWESOME_ICON_SOLID_FILE                                0x0000F35E
#define FONTAWESOME_ICON_SOLID_FILE_ALT                            0x0000F35F
#define FONTAWESOME_ICON_SOLID_FILE_ARCHIVE                        0x0000F360
#define FONTAWESOME_ICON_SOLID_FILE_AUDIO                          0x0000F361
#define FONTAWESOME_ICON_SOLID_FILE_CODE                           0x0000F362
#define FONTAWESOME_ICON_SOLID_FILE_EXCEL                          0x0000F363
#define FONTAWESOME_ICON_SOLID_FILE_IMAGE                          0x0000F364
#define FONTAWESOME_ICON_SOLID_FILE_PDF                            0x0000F365
#define FONTAWESOME_ICON_SOLID_FILE_POWERPOINT                     0x0000F366
#define FONTAWESOME_ICON_SOLID_FILE_VIDEO                          0x0000F367
#define FONTAWESOME_ICON_SOLID_FILE_WORD                           0x0000F368
#define FONTAWESOME_ICON_SOLID_FILM                                0x0000F369
#define FONTAWESOME_ICON_SOLID_FILTER                              0x0000F36A
#define FONTAWESOME_ICON_SOLID_FIRE                                0x0000F36B
#define FONTAWESOME_ICON_SOLID_FIRE_EXTINGUISHER                   0x0000F36C
#define FONTAWESOME_ICON_SOLID_FLAG                                0x0000F36D
#define FONTAWESOME_ICON_SOLID_FLAG_CHECKERED                      0x0000F36E
#define FONTAWESOME_ICON_SOLID_FLASK                               0x0000F36F
#define FONTAWESOME_ICON_SOLID_FOLDER                              0x0000F370
#define FONTAWESOME_ICON_SOLID_FOLDER_OPEN                         0x0000F371
#define FONTAWESOME_ICON_SOLID_FONT                                0x0000F372
#define FONTAWESOME_ICON_SOLID_FOOTBALL_BALL                       0x0000F373
#define FONTAWESOME_ICON_SOLID_FORWARD                             0x0000F374
#define FONTAWESOME_ICON_SOLID_FROWN                               0x0000F375
#define FONTAWESOME_ICON_SOLID_FUTBOL                              0x0000F376
#define FONTAWESOME_ICON_SOLID_GAMEPAD                             0x0000F377
#define FONTAWESOME_ICON_SOLID_GAVEL                               0x0000F378
#define FONTAWESOME_ICON_SOLID_GEM                                 0x0000F379
#define FONTAWESOME_ICON_SOLID_GENDERLESS                          0x0000F37A
#define FONTAWESOME_ICON_SOLID_GIFT                                0x0000F37B
#define FONTAWESOME_ICON_SOLID_GLASS_MARTINI                       0x0000F37C
#define FONTAWESOME_ICON_SOLID_GLOBE                               0x0000F37D
#define FONTAWESOME_ICON_SOLID_GOLF_BALL                           0x0000F37E
#define FONTAWESOME_ICON_SOLID_GRADUATION_CAP                      0x0000F37F
#define FONTAWESOME_ICON_SOLID_H_SQUARE                            0x0000F380
#define FONTAWESOME_ICON_SOLID_HAND_LIZARD                         0x0000F381
#define FONTAWESOME_ICON_SOLID_HAND_PAPER                          0x0000F382
#define FONTAWESOME_ICON_SOLID_HAND_PEACE                          0x0000F383
#define FONTAWESOME_ICON_SOLID_HAND_POINT_DOWN                     0x0000F384
#define FONTAWESOME_ICON_SOLID_HAND_POINT_LEFT                     0x0000F385
#define FONTAWESOME_ICON_SOLID_HAND_POINT_RIGHT                    0x0000F386
#define FONTAWESOME_ICON_SOLID_HAND_POINT_UP                       0x0000F387
#define FONTAWESOME_ICON_SOLID_HAND_POINTER                        0x0000F388
#define FONTAWESOME_ICON_SOLID_HAND_ROCK                           0x0000F389
#define FONTAWESOME_ICON_SOLID_HAND_SCISSORS                       0x0000F38A
#define FONTAWESOME_ICON_SOLID_HAND_SPOCK                          0x0000F38B
#define FONTAWESOME_ICON_SOLID_HANDSHAKE                           0x0000F38C
#define FONTAWESOME_ICON_SOLID_HASHTAG                             0x0000F38D
#define FONTAWESOME_ICON_SOLID_HDD                                 0x0000F38E
#define FONTAWESOME_ICON_SOLID_HEADING                             0x0000F38F
#define FONTAWESOME_ICON_SOLID_HEADPHONES                          0x0000F390
#define FONTAWESOME_ICON_SOLID_HEART                               0x0000F391
#define FONTAWESOME_ICON_SOLID_HEARTBEAT                           0x0000F392
#define FONTAWESOME_ICON_SOLID_HISTORY                             0x0000F393
#define FONTAWESOME_ICON_SOLID_HOCKEY_PUCK                         0x0000F394
#define FONTAWESOME_ICON_SOLID_HOME                                0x0000F395
#define FONTAWESOME_ICON_SOLID_HOSPITAL                            0x0000F396
#define FONTAWESOME_ICON_SOLID_HOURGLASS                           0x0000F397
#define FONTAWESOME_ICON_SOLID_HOURGLASS_END                       0x0000F398
#define FONTAWESOME_ICON_SOLID_HOURGLASS_HALF                      0x0000F399
#define FONTAWESOME_ICON_SOLID_HOURGLASS_START                     0x0000F39A
#define FONTAWESOME_ICON_SOLID_I_CURSOR                            0x0000F39B
#define FONTAWESOME_ICON_SOLID_ID_BADGE                            0x0000F39C
#define FONTAWESOME_ICON_SOLID_ID_CARD                             0x0000F39D
#define FONTAWESOME_ICON_SOLID_IMAGE                               0x0000F39E
#define FONTAWESOME_ICON_SOLID_IMAGES                              0x0000F39F
#define FONTAWESOME_ICON_SOLID_INBOX                               0x0000F3A0
#define FONTAWESOME_ICON_SOLID_INDENT                              0x0000F3A1
#define FONTAWESOME_ICON_SOLID_INDUSTRY                            0x0000F3A2
#define FONTAWESOME_ICON_SOLID_INFO                                0x0000F3A3
#define FONTAWESOME_ICON_SOLID_INFO_CIRCLE                         0x0000F3A4
#define FONTAWESOME_ICON_SOLID_ITALIC                              0x0000F3A5
#define FONTAWESOME_ICON_SOLID_KEY                                 0x0000F3A6
#define FONTAWESOME_ICON_SOLID_KEYBOARD                            0x0000F3A7
#define FONTAWESOME_ICON_SOLID_LANGUAGE                            0x0000F3A8
#define FONTAWESOME_ICON_SOLID_LAPTOP                              0x0000F3A9
#define FONTAWESOME_ICON_SOLID_LEAF                                0x0000F3AA
#define FONTAWESOME_ICON_SOLID_LEMON                               0x0000F3AB
#define FONTAWESOME_ICON_SOLID_LEVEL_DOWN_ALT                      0x0000F3AC
#define FONTAWESOME_ICON_SOLID_LEVEL_UP_ALT                        0x0000F3AD
#define FONTAWESOME_ICON_SOLID_LIFE_RING                           0x0000F3AE
#define FONTAWESOME_ICON_SOLID_LIGHTBULB                           0x0000F3AF
#define FONTAWESOME_ICON_SOLID_LINK                                0x0000F3B0
#define FONTAWESOME_ICON_SOLID_LIRA_SIGN                           0x0000F3B1
#define FONTAWESOME_ICON_SOLID_LIST                                0x0000F3B2
#define FONTAWESOME_ICON_SOLID_LIST_ALT                            0x0000F3B3
#define FONTAWESOME_ICON_SOLID_LIST_OL                             0x0000F3B4
#define FONTAWESOME_ICON_SOLID_LIST_UL                             0x0000F3B5
#define FONTAWESOME_ICON_SOLID_LOCATION_ARROW                      0x0000F3B6
#define FONTAWESOME_ICON_SOLID_LOCK                                0x0000F3B7
#define FONTAWESOME_ICON_SOLID_LOCK_OPEN                           0x0000F3B8
#define FONTAWESOME_ICON_SOLID_LONG_ARROW_ALT_DOWN                 0x0000F3B9
#define FONTAWESOME_ICON_SOLID_LONG_ARROW_ALT_LEFT                 0x0000F3BA
#define FONTAWESOME_ICON_SOLID_LONG_ARROW_ALT_RIGHT                0x0000F3BB
#define FONTAWESOME_ICON_SOLID_LONG_ARROW_ALT_UP                   0x0000F3BC
#define FONTAWESOME_ICON_SOLID_LOW_VISION                          0x0000F3BD
#define FONTAWESOME_ICON_SOLID_MAGIC                               0x0000F3BE
#define FONTAWESOME_ICON_SOLID_MAGNET                              0x0000F3BF
#define FONTAWESOME_ICON_SOLID_MALE                                0x0000F3C0
#define FONTAWESOME_ICON_SOLID_MAP                                 0x0000F3C1
#define FONTAWESOME_ICON_SOLID_MAP_MARKER                          0x0000F3C2
#define FONTAWESOME_ICON_SOLID_MAP_MARKER_ALT                      0x0000F3C3
#define FONTAWESOME_ICON_SOLID_MAP_PIN                             0x0000F3C4
#define FONTAWESOME_ICON_SOLID_MAP_SIGNS                           0x0000F3C5
#define FONTAWESOME_ICON_SOLID_MARS                                0x0000F3C6
#define FONTAWESOME_ICON_SOLID_MARS_DOUBLE                         0x0000F3C7
#define FONTAWESOME_ICON_SOLID_MARS_STROKE                         0x0000F3C8
#define FONTAWESOME_ICON_SOLID_MARS_STROKE_H                       0x0000F3C9
#define FONTAWESOME_ICON_SOLID_MARS_STROKE_V                       0x0000F3CA
#define FONTAWESOME_ICON_SOLID_MEDKIT                              0x0000F3CB
#define FONTAWESOME_ICON_SOLID_MEH                                 0x0000F3CC
#define FONTAWESOME_ICON_SOLID_MERCURY                             0x0000F3CD
#define FONTAWESOME_ICON_SOLID_MICROCHIP                           0x0000F3CE
#define FONTAWESOME_ICON_SOLID_MICROPHONE                          0x0000F3CF
#define FONTAWESOME_ICON_SOLID_MICROPHONE_SLASH                    0x0000F3D0
#define FONTAWESOME_ICON_SOLID_MINUS                               0x0000F3D1
#define FONTAWESOME_ICON_SOLID_MINUS_CIRCLE                        0x0000F3D2
#define FONTAWESOME_ICON_SOLID_MINUS_SQUARE                        0x0000F3D3
#define FONTAWESOME_ICON_SOLID_MOBILE                              0x0000F3D4
#define FONTAWESOME_ICON_SOLID_MOBILE_ALT                          0x0000F3D5
#define FONTAWESOME_ICON_SOLID_MONEY_BILL_ALT                      0x0000F3D6
#define FONTAWESOME_ICON_SOLID_MOON                                0x0000F3D7
#define FONTAWESOME_ICON_SOLID_MOTORCYCLE                          0x0000F3D8
#define FONTAWESOME_ICON_SOLID_MOUSE_POINTER                       0x0000F3D9
#define FONTAWESOME_ICON_SOLID_MUSIC                               0x0000F3DA
#define FONTAWESOME_ICON_SOLID_NEUTER                              0x0000F3DB
#define FONTAWESOME_ICON_SOLID_NEWSPAPER                           0x0000F3DC
#define FONTAWESOME_ICON_SOLID_OBJECT_GROUP                        0x0000F3DD
#define FONTAWESOME_ICON_SOLID_OBJECT_UNGROUP                      0x0000F3DE
#define FONTAWESOME_ICON_SOLID_OUTDENT                             0x0000F3DF
#define FONTAWESOME_ICON_SOLID_PAINT_BRUSH                         0x0000F3E0
#define FONTAWESOME_ICON_SOLID_PAPER_PLANE                         0x0000F3E1
#define FONTAWESOME_ICON_SOLID_PAPERCLIP                           0x0000F3E2
#define FONTAWESOME_ICON_SOLID_PARAGRAPH                           0x0000F3E3
#define FONTAWESOME_ICON_SOLID_PASTE                               0x0000F3E4
#define FONTAWESOME_ICON_SOLID_PAUSE                               0x0000F3E5
#define FONTAWESOME_ICON_SOLID_PAUSE_CIRCLE                        0x0000F3E6
#define FONTAWESOME_ICON_SOLID_PAW                                 0x0000F3E7
#define FONTAWESOME_ICON_SOLID_PEN_SQUARE                          0x0000F3E8
#define FONTAWESOME_ICON_SOLID_PENCIL_ALT                          0x0000F3E9
#define FONTAWESOME_ICON_SOLID_PERCENT                             0x0000F3EA
#define FONTAWESOME_ICON_SOLID_PHONE                               0x0000F3EB
#define FONTAWESOME_ICON_SOLID_PHONE_SQUARE                        0x0000F3EC
#define FONTAWESOME_ICON_SOLID_PHONE_VOLUME                        0x0000F3ED
#define FONTAWESOME_ICON_SOLID_PLANE                               0x0000F3EE
#define FONTAWESOME_ICON_SOLID_PLAY                                0x0000F3EF
#define FONTAWESOME_ICON_SOLID_PLAY_CIRCLE                         0x0000F3F0
#define FONTAWESOME_ICON_SOLID_PLUG                                0x0000F3F1
#define FONTAWESOME_ICON_SOLID_PLUS                                0x0000F3F2
#define FONTAWESOME_ICON_SOLID_PLUS_CIRCLE                         0x0000F3F3
#define FONTAWESOME_ICON_SOLID_PLUS_SQUARE                         0x0000F3F4
#define FONTAWESOME_ICON_SOLID_PODCAST                             0x0000F3F5
#define FONTAWESOME_ICON_SOLID_POUND_SIGN                          0x0000F3F6
#define FONTAWESOME_ICON_SOLID_POWER_OFF                           0x0000F3F7
#define FONTAWESOME_ICON_SOLID_PRINT                               0x0000F3F8
#define FONTAWESOME_ICON_SOLID_PUZZLE_PIECE                        0x0000F3F9
#define FONTAWESOME_ICON_SOLID_QRCODE                              0x0000F3FA
#define FONTAWESOME_ICON_SOLID_QUESTION                            0x0000F3FB
#define FONTAWESOME_ICON_SOLID_QUESTION_CIRCLE                     0x0000F3FC
#define FONTAWESOME_ICON_SOLID_QUIDDITCH                           0x0000F3FD
#define FONTAWESOME_ICON_SOLID_QUOTE_LEFT                          0x0000F3FE
#define FONTAWESOME_ICON_SOLID_QUOTE_RIGHT                         0x0000F3FF
#define FONTAWESOME_ICON_SOLID_RANDOM                              0x0000F400
#define FONTAWESOME_ICON_SOLID_RECYCLE                             0x0000F401
#define FONTAWESOME_ICON_SOLID_REDO                                0x0000F402
#define FONTAWESOME_ICON_SOLID_REDO_ALT                            0x0000F403
#define FONTAWESOME_ICON_SOLID_REGISTERED                          0x0000F404
#define FONTAWESOME_ICON_SOLID_REPLY                               0x0000F405
#define FONTAWESOME_ICON_SOLID_REPLY_ALL                           0x0000F406
#define FONTAWESOME_ICON_SOLID_RETWEET                             0x0000F407
#define FONTAWESOME_ICON_SOLID_ROAD                                0x0000F408
#define FONTAWESOME_ICON_SOLID_ROCKET                              0x0000F409
#define FONTAWESOME_ICON_SOLID_RSS                                 0x0000F40A
#define FONTAWESOME_ICON_SOLID_RSS_SQUARE                          0x0000F40B
#define FONTAWESOME_ICON_SOLID_RUBLE_SIGN                          0x0000F40C
#define FONTAWESOME_ICON_SOLID_RUPEE_SIGN                          0x0000F40D
#define FONTAWESOME_ICON_SOLID_SAVE                                0x0000F40E
#define FONTAWESOME_ICON_SOLID_SEARCH                              0x0000F40F
#define FONTAWESOME_ICON_SOLID_SEARCH_MINUS                        0x0000F410
#define FONTAWESOME_ICON_SOLID_SEARCH_PLUS                         0x0000F411
#define FONTAWESOME_ICON_SOLID_SERVER                              0x0000F412
#define FONTAWESOME_ICON_SOLID_SHARE                               0x0000F413
#define FONTAWESOME_ICON_SOLID_SHARE_ALT                           0x0000F414
#define FONTAWESOME_ICON_SOLID_SHARE_ALT_SQUARE                    0x0000F415
#define FONTAWESOME_ICON_SOLID_SHARE_SQUARE                        0x0000F416
#define FONTAWESOME_ICON_SOLID_SHEKEL_SIGN                         0x0000F417
#define FONTAWESOME_ICON_SOLID_SHIELD_ALT                          0x0000F418
#define FONTAWESOME_ICON_SOLID_SHIP                                0x0000F419
#define FONTAWESOME_ICON_SOLID_SHOPPING_BAG                        0x0000F41A
#define FONTAWESOME_ICON_SOLID_SHOPPING_BASKET                     0x0000F41B
#define FONTAWESOME_ICON_SOLID_SHOPPING_CART                       0x0000F41C
#define FONTAWESOME_ICON_SOLID_SHOWER                              0x0000F41D
#define FONTAWESOME_ICON_SOLID_SIGN_IN_ALT                         0x0000F41E
#define FONTAWESOME_ICON_SOLID_SIGN_LANGUAGE                       0x0000F41F
#define FONTAWESOME_ICON_SOLID_SIGN_OUT_ALT                        0x0000F420
#define FONTAWESOME_ICON_SOLID_SIGNAL                              0x0000F421
#define FONTAWESOME_ICON_SOLID_SITEMAP                             0x0000F422
#define FONTAWESOME_ICON_SOLID_SLIDERS_H                           0x0000F423
#define FONTAWESOME_ICON_SOLID_SMILE                               0x0000F424
#define FONTAWESOME_ICON_SOLID_SNOWFLAKE                           0x0000F425
#define FONTAWESOME_ICON_SOLID_SORT                                0x0000F426
#define FONTAWESOME_ICON_SOLID_SORT_ALPHA_DOWN                     0x0000F427
#define FONTAWESOME_ICON_SOLID_SORT_ALPHA_UP                       0x0000F428
#define FONTAWESOME_ICON_SOLID_SORT_AMOUNT_DOWN                    0x0000F429
#define FONTAWESOME_ICON_SOLID_SORT_AMOUNT_UP                      0x0000F42A
#define FONTAWESOME_ICON_SOLID_SORT_DOWN                           0x0000F42B
#define FONTAWESOME_ICON_SOLID_SORT_NUMERIC_DOWN                   0x0000F42C
#define FONTAWESOME_ICON_SOLID_SORT_NUMERIC_UP                     0x0000F42D
#define FONTAWESOME_ICON_SOLID_SORT_UP                             0x0000F42E
#define FONTAWESOME_ICON_SOLID_SPACE_SHUTTLE                       0x0000F42F
#define FONTAWESOME_ICON_SOLID_SPINNER                             0x0000F430
#define FONTAWESOME_ICON_SOLID_SQUARE                              0x0000F431
#define FONTAWESOME_ICON_SOLID_SQUARE_FULL                         0x0000F432
#define FONTAWESOME_ICON_SOLID_STAR                                0x0000F433
#define FONTAWESOME_ICON_SOLID_STAR_HALF                           0x0000F434
#define FONTAWESOME_ICON_SOLID_STEP_BACKWARD                       0x0000F435
#define FONTAWESOME_ICON_SOLID_STEP_FORWARD                        0x0000F436
#define FONTAWESOME_ICON_SOLID_STETHOSCOPE                         0x0000F437
#define FONTAWESOME_ICON_SOLID_STICKY_NOTE                         0x0000F438
#define FONTAWESOME_ICON_SOLID_STOP                                0x0000F439
#define FONTAWESOME_ICON_SOLID_STOP_CIRCLE                         0x0000F43A
#define FONTAWESOME_ICON_SOLID_STOPWATCH                           0x0000F43B
#define FONTAWESOME_ICON_SOLID_STREET_VIEW                         0x0000F43C
#define FONTAWESOME_ICON_SOLID_STRIKETHROUGH                       0x0000F43D
#define FONTAWESOME_ICON_SOLID_SUBSCRIPT                           0x0000F43E
#define FONTAWESOME_ICON_SOLID_SUBWAY                              0x0000F43F
#define FONTAWESOME_ICON_SOLID_SUITCASE                            0x0000F440
#define FONTAWESOME_ICON_SOLID_SUN                                 0x0000F441
#define FONTAWESOME_ICON_SOLID_SUPERSCRIPT                         0x0000F442
#define FONTAWESOME_ICON_SOLID_SYNC                                0x0000F443
#define FONTAWESOME_ICON_SOLID_SYNC_ALT                            0x0000F444
#define FONTAWESOME_ICON_SOLID_TABLE                               0x0000F445
#define FONTAWESOME_ICON_SOLID_TABLE_TENNIS                        0x0000F446
#define FONTAWESOME_ICON_SOLID_TABLET                              0x0000F447
#define FONTAWESOME_ICON_SOLID_TABLET_ALT                          0x0000F448
#define FONTAWESOME_ICON_SOLID_TACHOMETER_ALT                      0x0000F449
#define FONTAWESOME_ICON_SOLID_TAG                                 0x0000F44A
#define FONTAWESOME_ICON_SOLID_TAGS                                0x0000F44B
#define FONTAWESOME_ICON_SOLID_TASKS                               0x0000F44C
#define FONTAWESOME_ICON_SOLID_TAXI                                0x0000F44D
#define FONTAWESOME_ICON_SOLID_TERMINAL                            0x0000F44E
#define FONTAWESOME_ICON_SOLID_TEXT_HEIGHT                         0x0000F44F
#define FONTAWESOME_ICON_SOLID_TEXT_WIDTH                          0x0000F450
#define FONTAWESOME_ICON_SOLID_TH                                  0x0000F451
#define FONTAWESOME_ICON_SOLID_TH_LARGE                            0x0000F452
#define FONTAWESOME_ICON_SOLID_TH_LIST                             0x0000F453
#define FONTAWESOME_ICON_SOLID_THERMOMETER_EMPTY                   0x0000F454
#define FONTAWESOME_ICON_SOLID_THERMOMETER_FULL                    0x0000F455
#define FONTAWESOME_ICON_SOLID_THERMOMETER_HALF                    0x0000F456
#define FONTAWESOME_ICON_SOLID_THERMOMETER_QUARTER                 0x0000F457
#define FONTAWESOME_ICON_SOLID_THERMOMETER_THREE_QUARTERS          0x0000F458
#define FONTAWESOME_ICON_SOLID_THUMBS_DOWN                         0x0000F459
#define FONTAWESOME_ICON_SOLID_THUMBS_UP                           0x0000F45A
#define FONTAWESOME_ICON_SOLID_THUMBTACK                           0x0000F45B
#define FONTAWESOME_ICON_SOLID_TICKET_ALT                          0x0000F45C
#define FONTAWESOME_ICON_SOLID_TIMES                               0x0000F45D
#define FONTAWESOME_ICON_SOLID_TIMES_CIRCLE                        0x0000F45E
#define FONTAWESOME_ICON_SOLID_TINT                                0x0000F45F
#define FONTAWESOME_ICON_SOLID_TOGGLE_OFF                          0x0000F460
#define FONTAWESOME_ICON_SOLID_TOGGLE_ON                           0x0000F461
#define FONTAWESOME_ICON_SOLID_TRADEMARK                           0x0000F462
#define FONTAWESOME_ICON_SOLID_TRAIN                               0x0000F463
#define FONTAWESOME_ICON_SOLID_TRANSGENDER                         0x0000F464
#define FONTAWESOME_ICON_SOLID_TRANSGENDER_ALT                     0x0000F465
#define FONTAWESOME_ICON_SOLID_TRASH                               0x0000F466
#define FONTAWESOME_ICON_SOLID_TRASH_ALT                           0x0000F467
#define FONTAWESOME_ICON_SOLID_TREE                                0x0000F468
#define FONTAWESOME_ICON_SOLID_TROPHY                              0x0000F469
#define FONTAWESOME_ICON_SOLID_TRUCK                               0x0000F46A
#define FONTAWESOME_ICON_SOLID_TTY                                 0x0000F46B
#define FONTAWESOME_ICON_SOLID_TV                                  0x0000F46C
#define FONTAWESOME_ICON_SOLID_UMBRELLA                            0x0000F46D
#define FONTAWESOME_ICON_SOLID_UNDERLINE                           0x0000F46E
#define FONTAWESOME_ICON_SOLID_UNDO                                0x0000F46F
#define FONTAWESOME_ICON_SOLID_UNDO_ALT                            0x0000F470
#define FONTAWESOME_ICON_SOLID_UNIVERSAL_ACCESS                    0x0000F471
#define FONTAWESOME_ICON_SOLID_UNIVERSITY                          0x0000F472
#define FONTAWESOME_ICON_SOLID_UNLINK                              0x0000F473
#define FONTAWESOME_ICON_SOLID_UNLOCK                              0x0000F474
#define FONTAWESOME_ICON_SOLID_UNLOCK_ALT                          0x0000F475
#define FONTAWESOME_ICON_SOLID_UPLOAD                              0x0000F476
#define FONTAWESOME_ICON_SOLID_USER                                0x0000F477
#define FONTAWESOME_ICON_SOLID_USER_CIRCLE                         0x0000F478
#define FONTAWESOME_ICON_SOLID_USER_MD                             0x0000F479
#define FONTAWESOME_ICON_SOLID_USER_PLUS                           0x0000F47A
#define FONTAWESOME_ICON_SOLID_USER_SECRET                         0x0000F47B
#define FONTAWESOME_ICON_SOLID_USER_TIMES                          0x0000F47C
#define FONTAWESOME_ICON_SOLID_USERS                               0x0000F47D
#define FONTAWESOME_ICON_SOLID_UTENSIL_SPOON                       0x0000F47E
#define FONTAWESOME_ICON_SOLID_UTENSILS                            0x0000F47F
#define FONTAWESOME_ICON_SOLID_VENUS                               0x0000F480
#define FONTAWESOME_ICON_SOLID_VENUS_DOUBLE                        0x0000F481
#define FONTAWESOME_ICON_SOLID_VENUS_MARS                          0x0000F482
#define FONTAWESOME_ICON_SOLID_VIDEO                               0x0000F483
#define FONTAWESOME_ICON_SOLID_VOLLEYBALL_BALL                     0x0000F484
#define FONTAWESOME_ICON_SOLID_VOLUME_DOWN                         0x0000F485
#define FONTAWESOME_ICON_SOLID_VOLUME_OFF                          0x0000F486
#define FONTAWESOME_ICON_SOLID_VOLUME_UP                           0x0000F487
#define FONTAWESOME_ICON_SOLID_WHEELCHAIR                          0x0000F488
#define FONTAWESOME_ICON_SOLID_WIFI                                0x0000F489
#define FONTAWESOME_ICON_SOLID_WINDOW_CLOSE                        0x0000F48A
#define FONTAWESOME_ICON_SOLID_WINDOW_MAXIMIZE                     0x0000F48B
#define FONTAWESOME_ICON_SOLID_WINDOW_MINIMIZE                     0x0000F48C
#define FONTAWESOME_ICON_SOLID_WINDOW_RESTORE                      0x0000F48D
#define FONTAWESOME_ICON_SOLID_WON_SIGN                            0x0000F48E
#define FONTAWESOME_ICON_SOLID_WRENCH                              0x0000F48F
#define FONTAWESOME_ICON_SOLID_YEN_SIGN                            0x0000F490
#define FONTAWESOME_ICON_SQUARE                                    0x0000F491
#define FONTAWESOME_ICON_STAR                                      0x0000F492
#define FONTAWESOME_ICON_STAR_HALF                                 0x0000F493
#define FONTAWESOME_ICON_STICKY_NOTE                               0x0000F494
#define FONTAWESOME_ICON_STOP_CIRCLE                               0x0000F495
#define FONTAWESOME_ICON_SUN                                       0x0000F496
#define FONTAWESOME_ICON_THUMBS_DOWN                               0x0000F497
#define FONTAWESOME_ICON_THUMBS_UP                                 0x0000F498
#define FONTAWESOME_ICON_TIMES_CIRCLE                              0x0000F499
#define FONTAWESOME_ICON_TRASH_ALT                                 0x0000F49A
#define FONTAWESOME_ICON_USER                                      0x0000F49B
#define FONTAWESOME_ICON_USER_CIRCLE                               0x0000F49C
#define FONTAWESOME_ICON_WINDOW_CLOSE                              0x0000F49D
#define FONTAWESOME_ICON_WINDOW_MAXIMIZE                           0x0000F49E
#define FONTAWESOME_ICON_WINDOW_MINIMIZE                           0x0000F49F
#define FONTAWESOME_ICON_WINDOW_RESTORE                            0x0000F4A0
